version: '3.8'

x-router-base: &router_base
  cap_add:
    - NET_ADMIN
  build:
    context: ./roteador
    dockerfile: Dockerfile

x-host-base: &host_base
  cap_add:
    - NET_ADMIN
  build:
    context: ./host
    dockerfile: Dockerfile

services:

  roteador1:
    <<: *router_base
    container_name: roteador1
    environment:
      - ROTEADOR_ID=roteador1
      - ENDERECO_IP=172.21.0.2
      - VIZINHOS={ "roteador2":["172.21.1.2",10],"roteador3":["172.21.2.2",10],"roteador4":["172.21.3.2",10] }
    networks:

      rede1:
        ipv4_address: 172.21.0.2

      rede2:
        ipv4_address: 172.21.1.3

      rede3:
        ipv4_address: 172.21.2.3

      rede4:
        ipv4_address: 172.21.3.3


  roteador2:
    <<: *router_base
    container_name: roteador2
    environment:
      - ROTEADOR_ID=roteador2
      - ENDERECO_IP=172.21.1.2
      - VIZINHOS={ "roteador1":["172.21.0.2",10],"roteador3":["172.21.2.2",10],"roteador4":["172.21.3.2",10] }
    networks:

      rede2:
        ipv4_address: 172.21.1.2

      rede1:
        ipv4_address: 172.21.0.4

      rede3:
        ipv4_address: 172.21.2.4

      rede4:
        ipv4_address: 172.21.3.4


  roteador3:
    <<: *router_base
    container_name: roteador3
    environment:
      - ROTEADOR_ID=roteador3
      - ENDERECO_IP=172.21.2.2
      - VIZINHOS={ "roteador1":["172.21.0.2",10],"roteador2":["172.21.1.2",10],"roteador4":["172.21.3.2",10] }
    networks:

      rede3:
        ipv4_address: 172.21.2.2

      rede1:
        ipv4_address: 172.21.0.5

      rede2:
        ipv4_address: 172.21.1.5

      rede4:
        ipv4_address: 172.21.3.5


  roteador4:
    <<: *router_base
    container_name: roteador4
    environment:
      - ROTEADOR_ID=roteador4
      - ENDERECO_IP=172.21.3.2
      - VIZINHOS={ "roteador1":["172.21.0.2",10],"roteador2":["172.21.1.2",10],"roteador3":["172.21.2.2",10] }
    networks:

      rede4:
        ipv4_address: 172.21.3.2

      rede1:
        ipv4_address: 172.21.0.6

      rede2:
        ipv4_address: 172.21.1.6

      rede3:
        ipv4_address: 172.21.2.6




  host1a:
    <<: *host_base
    container_name: host1a
    environment:
      - ROTEADOR_CONECTADO= 172.21.0.2
    networks:
      rede1:
        ipv4_address: 172.21.0.10

  host1b:
    <<: *host_base
    container_name: host1b
    environment:
      - ROTEADOR_CONECTADO= 172.21.0.2
    networks:
      rede1:
        ipv4_address: 172.21.0.11

  host2a:
    <<: *host_base
    container_name: host2a
    environment:
      - ROTEADOR_CONECTADO= 172.21.1.2
    networks:
      rede2:
        ipv4_address: 172.21.1.10

  host2b:
    <<: *host_base
    container_name: host2b
    environment:
      - ROTEADOR_CONECTADO= 172.21.1.2
    networks:
      rede2:
        ipv4_address: 172.21.1.11

  host3a:
    <<: *host_base
    container_name: host3a
    environment:
      - ROTEADOR_CONECTADO= 172.21.2.2
    networks:
      rede3:
        ipv4_address: 172.21.2.10

  host3b:
    <<: *host_base
    container_name: host3b
    environment:
      - ROTEADOR_CONECTADO= 172.21.2.2
    networks:
      rede3:
        ipv4_address: 172.21.2.11

  host4a:
    <<: *host_base
    container_name: host4a
    environment:
      - ROTEADOR_CONECTADO= 172.21.3.2
    networks:
      rede4:
        ipv4_address: 172.21.3.10

  host4b:
    <<: *host_base
    container_name: host4b
    environment:
      - ROTEADOR_CONECTADO= 172.21.3.2
    networks:
      rede4:
        ipv4_address: 172.21.3.11


networks:

  rede1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

  rede2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1

  rede3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.2.0/24
          gateway: 172.21.2.1

  rede4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.3.0/24
          gateway: 172.21.3.1
